---
- hosts: all
  become: yes
  tasks:
          - copy:
              content: "welcome to AUS"
              dest: /tmp/newzeland
            notify: restart_apache

  handlers:
          - name: restart_apache
            service: 
              name: http
              state: restarted
              enabled: yes
              
...
