---
- hosts: all
  become: yes
  tasks:
    - copy:
        content: "Mangal Singh RHCA 2023"
        dest: /tmp/abc.txt
      notify: restart_httpd
  handlers:
    - name: restart_httpd
      service:
        name: httpd
        state: restart
        enabled: yes
